GET http://localhost:5190/games

###
GET http://localhost:5190/games/6
###
POST  http://localhost:5190/games
Content-Type: application/json

{
  "name": "Call of Duty: Modern Warfare",
  "genreId": 4,
  "price": 59.99,
  "releaseDate": "2023-10-01"
}

###
PUT  http://localhost:5190/games/6
Content-Type: application/json

{
  "name": "Updated Game Title",
  "genreId": 1,
  "price": 20.99,
  "releaseDate": "2023-11-01"
}

###

DELETE http://localhost:5190/games/1
Content-Type: application/json

